### ISSUE TITLE
NAS542 wrong script to install kernel

### ISSUE THREAD

**Issue by AdamWeglarz** [scpcom/linux#2]
Hi,

When installing kernel it provides error:
./install-linux.sh: 73: Bad substitution
It is present in all builds from 5.x.y to 6.1.67
All kdtb install part in problematic. When you comment  line 73 other occurs also with substitution:
 ./install-linux.sh: 93: Bad substitution

Adam

**Comment by scpcom** [comment]
Hi,

The scripts are made for bash, you can run them with:
`bash -e ./install-linux.sh`
