### ISSUE TITLE
Build process on x86 PC does not provide .deb files

### ISSUE THREAD

**Issue by AdamWeglarz** [scpcom/linux#5]
Hi,

I am compiling kernel (I understand that script support cross-compilation on x86) based on instruction on Debian 12 with kernel 6.1.0-17-amd64
http://seafile.servator.de/nas/zyxel/build/nas5xx-kernel-build.txt
and even though there are no issues I do not have any files I got on my nas generetaed during previous compilation (which were working fine).
like (one of previous builds I have made):
linux-headers-6.1.67+nas5xx_6.1.67-20231214-nas5xx_armhf.deb
 linux-image-6.1.67+nas5xx_6.1.67-20231214-nas5xx_armhf.deb
linux-image-6.1.67-20231214-nas5xx-armhf.zip
linux-libc-dev_6.1.67-20231214-nas5xx_armhf.deb
linux-setup-nas5xx_6.1.67-20231214-nas5xx_armhf.deb
linux-upstream_6.1.67-20231214-nas5xx_armhf.buildinfo

Compiling on nas it is like 24hours so it would be useful to be able to compile on x86 more performant machine.

Adam

**Comment by AdamWeglarz** [comment]
The same compilation directly on nas worked great and I have finally solved my problem :-)

**Comment by scpcom** [comment]
Thanks for reporting.
Yes building on the NAS always works but is veeeery slow :-)
I tried cross compile on a different machine and found a missing tool, you can get it with:
`sudo apt-get install u-boot-tools`
